services:
  golang-container:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./code:/app/code
    working_dir: /app
    tty: true
    stdin_open: true
    restart: no
    container_name: graphql-golang-container
